### ISSUE TITLE
DNS does not resolve pre-prod environments

### ISSUE THREAD

**Issue by steppenwells** [guardian/machine-images#14]
I'm trying to get the CODE tag api up and running, this requires the DNS feature to allow it to get at R2 and ingest the tags.

Unfortunately the DNS feature allows the production url to be resolved but not the equivalent code address. Clearly it would be useful to be able to resolve all of our estate

```
ubuntu@ip-10-248-127-114:/home/tagApi/logs$ curl http://r2.code.dev-gutools.co.uk/tools/index
curl: (6) Could not resolve host: r2.code.dev-gutools.co.uk

ubuntu@ip-10-248-127-114:/home/tagApi/logs$ curl http://cms.guprod.gnl/tools/index
<!DOCTYPE html><html lang="en">
<style type="text/css">
    body {
        font-family:Geneva,Arial,sans-serif;
...
```

**Comment by sihil** [comment]
I got to the bottom of this. It's due to r2.code.dev-gutools.co.uk being a recursive lookup as it has a CNAME in it. In this case it fails because the target DNS server isn't authoritative for the gudev.gnm domain which is part of the resolution chain.

I've raised a JIRA ticket https://jira.gutools.co.uk/browse/WSF-690 so websys can address this and possibly also address anything that resolves to an external address.

**Comment by sihil** [comment]
The missing zone has now been added to the source DNS server and `r2.code.dev-gutools.co.uk` resolves correctly.

/cc @tpemckiernan

**Comment by tpemckiernan** [comment]
I still get the same issue. Do we need to pick up a new machine image or should existing images see the change?
ubuntu@ip-10-248-126-67:~$ curl http://r2.code.dev-gutools.co.uk/tools/index
curl: (6) Could not resolve host: r2.code.dev-gutools.co.uk
ubuntu@ip-10-248-126-67:~$

**Comment by sihil** [comment]
Existing images should see the change.

On Thu, 14 May 2015 at 12:31 Thomas McKiernan notifications@github.com
wrote:

> I still get the same issue. Do we need to pick up a new machine image or
> should existing images see the change?
> ubuntu@ip-10-248-126-67:~$ curl
> http://r2.code.dev-gutools.co.uk/tools/index
> 
> curl: (6) Could not resolve host: r2.code.dev-gutools.co.uk
> 
> ubuntu@ip-10-248-126-67:~$
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/guardian/machine-images/issues/14#issuecomment-102008435
> .

## 

---

Visit theguardian.com. On your mobile and tablet, download the Guardian 
iPhone and Android apps theguardian.com/guardianapp and our tablet editions 
theguardian.com/editions.  Save up to 57% by subscribing to the Guardian 
and Observer - choose the papers you want and get full digital access. 
 Visit subscribe.theguardian.com

This e-mail and all attachments are confidential and may also be 
privileged. If you are not the named recipient, please notify the sender 
and delete the e-mail and all attachments immediately. Do not disclose the 
contents to another person. You may not use the information for any 
purpose, or store, or copy, it in any way.  Guardian News & Media Limited 
is not liable for any computer viruses or other material transmitted with 
or as part of this e-mail. You should employ virus checking software.

Guardian News & Media Limited is a member of Guardian Media Group plc. Registered 
Office: PO Box 68164, Kings Place, 90 York Way, London, N1P 2AP.  Registered 
in England Number 908396

**Comment by sihil** [comment]
Nope - take that back. Needs a change to the machine images as well.

https://github.com/guardian/machine-images/pull/17

On Thu, 14 May 2015 at 12:32 Simon Hildrew simon.hildrew@theguardian.com
wrote:

> Existing images should see the change.
> 
> On Thu, 14 May 2015 at 12:31 Thomas McKiernan notifications@github.com
> wrote:
> 
> > I still get the same issue. Do we need to pick up a new machine image or
> > should existing images see the change?
> > ubuntu@ip-10-248-126-67:~$ curl
> > http://r2.code.dev-gutools.co.uk/tools/index
> > 
> > curl: (6) Could not resolve host: r2.code.dev-gutools.co.uk
> > 
> > ubuntu@ip-10-248-126-67:~$
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/guardian/machine-images/issues/14#issuecomment-102008435
> > .

## 

---

Visit theguardian.com. On your mobile and tablet, download the Guardian 
iPhone and Android apps theguardian.com/guardianapp and our tablet editions 
theguardian.com/editions.  Save up to 57% by subscribing to the Guardian 
and Observer - choose the papers you want and get full digital access. 
 Visit subscribe.theguardian.com

This e-mail and all attachments are confidential and may also be 
privileged. If you are not the named recipient, please notify the sender 
and delete the e-mail and all attachments immediately. Do not disclose the 
contents to another person. You may not use the information for any 
purpose, or store, or copy, it in any way.  Guardian News & Media Limited 
is not liable for any computer viruses or other material transmitted with 
or as part of this e-mail. You should employ virus checking software.

Guardian News & Media Limited is a member of Guardian Media Group plc. Registered 
Office: PO Box 68164, Kings Place, 90 York Way, London, N1P 2AP.  Registered 
in England Number 908396

**Comment by sihil** [comment]
You can temporarily add the new zone to /etc/dnsmasq.d/gnm.conf as a
workaround.

On Thu, 14 May 2015 at 12:37 Simon Hildrew simon.hildrew@theguardian.com
wrote:

> Nope - take that back. Needs a change to the machine images as well.
> 
> https://github.com/guardian/machine-images/pull/17
> 
> On Thu, 14 May 2015 at 12:32 Simon Hildrew simon.hildrew@theguardian.com
> wrote:
> 
> > Existing images should see the change.
> > 
> > On Thu, 14 May 2015 at 12:31 Thomas McKiernan notifications@github.com
> > wrote:
> > 
> > > I still get the same issue. Do we need to pick up a new machine image or
> > > should existing images see the change?
> > > ubuntu@ip-10-248-126-67:~$ curl
> > > http://r2.code.dev-gutools.co.uk/tools/index
> > > 
> > > curl: (6) Could not resolve host: r2.code.dev-gutools.co.uk
> > > 
> > > ubuntu@ip-10-248-126-67:~$
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub
> > > https://github.com/guardian/machine-images/issues/14#issuecomment-102008435
> > > .

## 

---

Visit theguardian.com. On your mobile and tablet, download the Guardian 
iPhone and Android apps theguardian.com/guardianapp and our tablet editions 
theguardian.com/editions.  Save up to 57% by subscribing to the Guardian 
and Observer - choose the papers you want and get full digital access. 
 Visit subscribe.theguardian.com

This e-mail and all attachments are confidential and may also be 
privileged. If you are not the named recipient, please notify the sender 
and delete the e-mail and all attachments immediately. Do not disclose the 
contents to another person. You may not use the information for any 
purpose, or store, or copy, it in any way.  Guardian News & Media Limited 
is not liable for any computer viruses or other material transmitted with 
or as part of this e-mail. You should employ virus checking software.

Guardian News & Media Limited is a member of Guardian Media Group plc. Registered 
Office: PO Box 68164, Kings Place, 90 York Way, London, N1P 2AP.  Registered 
in England Number 908396

**Comment by tpemckiernan** [comment]
thx

**Comment by sihil** [comment]
The latest AMI should fix this.

**Comment by tpemckiernan** [comment]
confirmed, works grt
