### ISSUE TITLE
Migrate the Java8 image to use Utopic

### ISSUE THREAD

**Issue by sihil** [guardian/machine-images#8]
We are using a backport of java8 from utopic. We should really just use utopic instead of trusty. I'm not concerned about the LTS status - provided we follow through with out housekeeping tools around making sure we don't have images > X months in use.

**Comment by rich-nguyen** [comment]
I'm keen on this. Also, I remembered what issues we were having with reference java 8; our jdk tools were not working. So if everything is hunky dory with your packer build, we'll go to utopic and take your installation of reference java 8 (will discuss how we do this at some point).

**Comment by sihil** [comment]
Superseded by #16 IMHO - closing unless any objections.

**Comment by rich-nguyen** [comment]
Yes, makes sense, assuming a java 8 image is part of the work for ubuntu 15.04.

**Comment by sihil** [comment]
There is already a java8 image, so that'll be updated appropriately.

**Comment by cb372** [comment]
In the meantime I'm going to update the Java 8 image to use the latest Java 8 package from the 15.04 repo, so we can get the most up-to-date Java possible. I'll make a separate PR for that.
